--- #YAML:1.0
name: Graph-Easy-Manual
version: 0.28
version_from: lib/Graph/Easy/Manual.pm
license: gpl
distribution_type: module
generated_by: Graph-Easy-Manual version 0.28
installdirs: site
requires:
  File::Spec: 3.01
  Graph::Easy: 0.39
  Pod::Simple: 3.02
