abstract: HTML manual for Graph::Easy
author: Tels <nospam-abuse@bloodgate.com>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.63
license: gpl
name: Graph-Easy-Manual
no_index: 
  directory: 
    - examples
    - inc
    - t
recommends: 
  Graph::Easy::As_svg: 0.19
requires: 
  File::Spec: 3.01
  Graph::Easy: 0.46
  Pod::Simple: 3.02
version: 0.33
